#!/bin/sh

# A dmenu wrapper script for system functions.

# For non-systemd init systems.
case "$(readlink -f /sbin/init)" in
	*runit*) sus="sudo -A zzz" ;;
	*openrc*) reb="sudo -A openrc-shutdown -r"; shut="sudo -A openrc-shutdown -p 0" ;;
esac

cmds="\
 Lock		slock
 Suspend	slock ${sus}
 Reboot	        ${reb:-sudo -A reboot}
 Shutdown	${shut:-sudo -A shutdown -h now}"

choice="$(echo "$cmds" | cut -d'	' -f 1 | dmenu)" || exit 1

eval "$(echo "$cmds" | grep "^$choice	" | cut -d '	' -f2-)"
