#!/bin/sh

manual=$(apropos -s ${SECTION:-''} ${@:-.} | \
    grep -v -E '^.+ \(0\)' |\
    awk '{print $2 "    " $1}' | \
    sort | \
    dmenu -i -p "Manual: " | \
    sed -E 's/^\((.+)\)/\1/')

[ -z "$manual" ] && exit 0
man "$manual"

