#!/bin/sh

# This is a ssh key generator for my purpose
ssh-keygen -t ed25519 -C "ashin"
eval "$(ssh-agent -s)"
ssh-add /home/ashin/.ssh/id_ed25519

{
	echo "# GitLab.com" >>/home/ashin/.ssh/config
	echo "Host gitlab.com " >>/home/ashin/.ssh/config
	echo "PreferredAuthentications publickey" >>/home/ashin/.ssh/config
	echo "IdentityFile ~/.ssh/id_ed25519" >>/home/ashin/.ssh/config

	echo "# GitHub.com" >>/home/ashin/.ssh/config
	echo "Host github.com" >>/home/ashin/.ssh/config
	echo "PreferredAuthentications publickey" >>/home/ashin/.ssh/config
	echo "IdentityFile ~/.ssh/id_ed25519" >>/home/ashin/.ssh/config
} >>/home/ashin/.ssh/config
